# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# IntelliJ IDEA is not yet fully compatible with configuration cache
org.gradle.configuration-cache=false

# Proxy settings - uncomment locally if behind a proxy (needed for CI? no)
# systemProp.http.proxyHost=127.0.0.1
# systemProp.http.proxyPort=7890
# systemProp.https.proxyHost=127.0.0.1
# systemProp.https.proxyPort=7890

# Fabric Properties
# latest versions from https://fabricmc.net/develop
minecraft_version=26.1
loader_version=0.19.2
loom_version=1.16-SNAPSHOT

# Mod Properties
mod_version=1.2.0
maven_group=betterbundle

# Dependencies
fabric_api_version=0.145.1+26.1
quickshulker_version=3.2.7-mc26.1.2
